In [2]:
import numpy as np
from numpy import random
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
a2 = np.array([2,4,6,8])

In [4]:
a1 + a2

array([ 3,  6,  9, 12])

In [5]:
a1-a2

array([-1, -2, -3, -4])

In [6]:
a1 * a2

array([ 2,  8, 18, 32])

In [7]:
a1 / a2

array([0.5, 0.5, 0.5, 0.5])

In [8]:
np.dot(a1,a2)

60

In [9]:
a3 = np.random.randint(100,size = (2,3))

In [10]:
a3

array([[74, 22, 59],
       [74, 33, 44]])

In [11]:
a4 = np.random.randint(100,size = (4))

In [12]:
a4

array([90, 84, 22, 88])

In [13]:
a5 = random.rand(4)

In [14]:
a5

array([0.2709725 , 0.61419557, 0.6291832 , 0.96446019])

In [15]:
random.choice(a5)

0.6291832042356277

In [16]:
a5.sum()

2.478811457337868

In [17]:
a3

array([[74, 22, 59],
       [74, 33, 44]])

In [18]:
a3.sum(axis=0)
a3

array([[74, 22, 59],
       [74, 33, 44]])

In [19]:
a3.cumsum(axis=0)

array([[ 74,  22,  59],
       [148,  55, 103]])

In [20]:
a3.cumsum(axis=1)

array([[ 74,  96, 155],
       [ 74, 107, 151]])

In [21]:
a3.max()

74

In [22]:
a3.min()

22

In [23]:
np.add(a3,5)

array([[79, 27, 64],
       [79, 38, 49]])

In [24]:
a8 = random.randint(100,size=(2,3))
np.add(a3,a8)

array([[169,  40,  93],
       [118,  47, 122]])

In [25]:
subaray = np.subtract(a3,a8)
subaray

array([[-21,   4,  25],
       [ 30,  19, -34]])

In [26]:
np.multiply(a3,a8)

array([[7030,  396, 2006],
       [3256,  462, 3432]])

In [27]:
np.divide(a3,a8)

array([[0.77894737, 1.22222222, 1.73529412],
       [1.68181818, 2.35714286, 0.56410256]])

In [28]:
np.remainder(a3,a8)

array([[74,  4, 25],
       [30,  5, 44]])

In [29]:
np.power(a3,a8)

array([[                   0,  3268220242146623488,  1560809105612572953],
       [-3921210308370104320,  8550762560264564161,                    0]])

In [30]:
np.sqrt(a3)

array([[8.60232527, 4.69041576, 7.68114575],
       [8.60232527, 5.74456265, 6.63324958]])

In [31]:
a9 = np.cbrt(a3)
a9

array([[4.19833645, 2.80203933, 3.89299642],
       [4.19833645, 3.20753433, 3.53034834]])

In [32]:
np.absolute(subaray)

array([[21,  4, 25],
       [30, 19, 34]])

In [49]:
a3

array([[74, 22, 59],
       [74, 33, 44]])

In [51]:
expa = np.exp(a3)
expa

array([[1.37338298e+32, 3.58491285e+09, 4.20121040e+25],
       [1.37338298e+32, 2.14643580e+14, 1.28516001e+19]])

In [53]:
z=np.ceil(expa)
z

array([[1.37338298e+32, 3.58491285e+09, 4.20121040e+25],
       [1.37338298e+32, 2.14643580e+14, 1.28516001e+19]])

In [35]:
np.log2(a3)

array([[6.20945337, 4.45943162, 5.88264305],
       [6.20945337, 5.04439412, 5.45943162]])

In [36]:
np.log10(a3)

array([[1.86923172, 1.34242268, 1.77085201],
       [1.86923172, 1.51851394, 1.64345268]])

In [37]:
np.gcd.reduce([9,12,15])

3

In [38]:
np.lcm.reduce([9,12,15,18,21])

1260

In [39]:
np.floor(a3)

array([[74., 22., 59.],
       [74., 33., 44.]])

In [40]:

print(a3)

[[74 22 59]
 [74 33 44]]


In [41]:
np.ceil(a3)

array([[74., 22., 59.],
       [74., 33., 44.]])

In [42]:
a10 = np.random.randint(10,size=(5,3))

a10

array([[1, 7, 1],
       [5, 0, 6],
       [9, 3, 1],
       [4, 6, 4],
       [9, 9, 9]])

In [54]:
a10.argmax(axis=0)

array([2, 4, 4])

In [44]:
index = a10.argmax(axis=0)

In [45]:
index

array([2, 4, 4])

In [46]:
index2 = a10.argmax(axis=1)

In [47]:
index2

array([1, 2, 0, 1, 0])

In [48]:
sqarray = np.arange(6) ** 2
sqarray

array([ 0,  1,  4,  9, 16, 25])