# Linear Algebra

In [3]:
import numpy as np

In [4]:
from numpy import random
from numpy import linalg as la

In [5]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

The dot product of two vectors a = [a1, a2, …, an] and b = [b1, b2, …, bn] is defined as:
    

<img src = "dp.png">

a1.a2 = (1 * 4) + (2 * 5) + (3 * 6)

In [6]:
np.dot(a1,a2)

32

In [7]:
mdA = np.random.random((10, 4))
mdB = np.random.random((4, 6))
mdC = np.random.random((6, 20))

la.multi_dot([mdA,mdB,mdC])

array([[1.47713076, 4.87699456, 4.20721342, 4.37964639, 2.91809624,
        3.22942791, 2.96815685, 3.09293858, 2.92172074, 4.48545025,
        3.43089459, 4.40818821, 4.04814147, 3.69071783, 2.68782677,
        3.52679217, 3.25625363, 3.93919851, 4.24987734, 4.58887926],
       [0.77443432, 2.71838304, 2.52409066, 2.53217481, 1.69126575,
        1.74932138, 1.67476096, 1.80188241, 1.61167438, 2.75951742,
        2.00762718, 2.47101634, 2.38244687, 2.11378944, 1.55247699,
        2.11242273, 1.84170862, 2.09791266, 2.43315013, 2.56697559],
       [0.83774504, 2.6463714 , 2.24897961, 2.32938417, 1.58481243,
        1.7841047 , 1.60054212, 1.70546118, 1.59437388, 2.39289879,
        1.84136285, 2.36159594, 2.1391109 , 2.01526502, 1.43256513,
        1.93489178, 1.75707441, 2.19363126, 2.31558185, 2.46666453],
       [1.01682855, 3.5678764 , 3.24072078, 3.18729875, 2.2328605 ,
        2.1854715 , 2.18750201, 2.17848158, 1.90285888, 3.46989704,
        2.64844842, 3.21387805, 2.93157539, 2

In [8]:
np.inner(a1,a2)

32

In [9]:
a4 = ([[[1,2],[3,4]],[[5,6],[7,8]]])

In [10]:
a4

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [11]:
a5 = ([1,2],[3,4])

In [12]:
np.tensordot(a4,a5)

array([30, 70])

In [13]:
a6 = np.array([0,5])
a7 = np.array([[1,2,3,4],[5,6,7,8]], dtype = object)

In [14]:
np.einsum('i ->',a6)

5

In [18]:
squarematrix =np.array([[1,2],[3,1]])
la.matrix_power(squarematrix,2)


array([[7, 4],
       [6, 7]])

In [17]:
a8 = np.array([[1,2],[3,4]])

In [32]:
la.matrix_power(a8,2)

array([[ 7, 10],
       [15, 22]])

In [33]:
np.kron(a1,a2)

array([ 4,  5,  6,  8, 10, 12, 12, 15, 18])

In [35]:
la.eig(a8)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [36]:
la.norm(a8)

5.477225575051661

In [37]:
la.eigvals(a8)

array([-0.37228132,  5.37228132])

In [40]:
la.cond(a8)

14.933034373659268

In [42]:
print(a8)
la.det(a8)

[[1 2]
 [3 4]]


-2.0000000000000004

In [43]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [55]:
a9 = np.array([[3,2],[1,3]])
ans = np.array([2,5])
la.solve(a9,ans)

array([-0.57142857,  1.85714286])

In [47]:
la.solve(a8,a9)

array([[ 1. , -1. ],
       [-0.5,  1.5]])

In [48]:
np.diag(a8)

array([1, 4])

In [49]:
a10 = random.randint(20,size=(5,5))

In [50]:
a10

array([[18,  2,  9, 13, 16],
       [ 7, 18, 19, 16, 18],
       [19, 19, 11,  2, 15],
       [ 8,  6, 15, 11, 16],
       [ 7, 11,  6, 10, 11]])

In [51]:
np.einsum('ii->i', a10)

array([18, 18, 11, 11, 11])

In [53]:
np.einsum('ij->i', a10)

array([58, 78, 66, 56, 45])

In [54]:
np.einsum('ji->i', a10)

array([59, 56, 60, 52, 76])