In [1]:
import numpy as np
from numpy import random

In [2]:
lis = [1,2,3,4]
array1 = np.array(lis)

In [3]:
array1


array([1, 2, 3, 4])

In [11]:
randarray = np.random.randint(1, 20, size=(10,3))

In [12]:
randarray

array([[ 6, 12, 12],
       [13,  4,  9],
       [ 8, 14,  3],
       [ 1, 12, 11],
       [18, 11, 13],
       [ 2, 18, 11],
       [16,  3,  9],
       [16, 15,  8],
       [ 3,  8,  4],
       [13, 15,  5]])

In [14]:
randarray[5,1]

18

In [15]:
randarray.itemset((0,1),5)

In [16]:
randarray

array([[ 6,  5, 12],
       [13,  4,  9],
       [ 8, 14,  3],
       [ 1, 12, 11],
       [18, 11, 13],
       [ 2, 18, 11],
       [16,  3,  9],
       [16, 15,  8],
       [ 3,  8,  4],
       [13, 15,  5]])

In [19]:
randarray.shape

(10, 3)

In [18]:
randarray.item(0,2)

12

In [20]:
randarray[::-1]

array([[13, 15,  5],
       [ 3,  8,  4],
       [16, 15,  8],
       [16,  3,  9],
       [ 2, 18, 11],
       [18, 11, 13],
       [ 1, 12, 11],
       [ 8, 14,  3],
       [13,  4,  9],
       [ 6,  5, 12]])

In [21]:
randarray[:10:2]

array([[ 6,  5, 12],
       [ 8, 14,  3],
       [18, 11, 13],
       [16,  3,  9],
       [ 3,  8,  4]])

In [22]:
even = randarray[randarray%2 == 0]
even

array([ 6, 12,  4,  8, 14, 12, 18,  2, 18, 16, 16,  8,  8,  4])

In [23]:
randarray

array([[ 6,  5, 12],
       [13,  4,  9],
       [ 8, 14,  3],
       [ 1, 12, 11],
       [18, 11, 13],
       [ 2, 18, 11],
       [16,  3,  9],
       [16, 15,  8],
       [ 3,  8,  4],
       [13, 15,  5]])

In [24]:
randarray[randarray >12]

array([13, 14, 18, 13, 18, 16, 16, 15, 13, 15])

In [25]:
randarray[(randarray >12) & (randarray <18)]

array([13, 14, 13, 16, 16, 15, 13, 15])

In [26]:
np.unique(randarray)

array([ 1,  2,  3,  4,  5,  6,  8,  9, 11, 12, 13, 14, 15, 16, 18])

In [27]:
np.take(randarray,[12])

array([18])

In [30]:
np.put(randarray,[0],[5])

In [31]:
randarray

array([[ 5,  5, 12],
       [13,  4,  9],
       [ 8, 14,  3],
       [ 1, 12, 11],
       [ 5, 11, 13],
       [ 2, 18, 11],
       [16,  3,  9],
       [16, 15,  8],
       [ 3,  8,  4],
       [13, 15,  5]])

In [32]:
randarray[(randarray == 12) | (randarray  == 18)]

array([12, 12, 18])