In [1]:
import numpy as np
from numpy import random

In [2]:
a1 = np.random.randint(10,size=(3,3))
a1
print("a1", a1)
a2 = np.random.randint(10,size = (3,3))
a2
print("a2", a2)

a1 [[6 6 4]
 [3 1 1]
 [3 5 4]]
a2 [[6 7 1]
 [3 0 2]
 [3 6 1]]


In [3]:
np.vstack((a1,a2))

array([[6, 6, 4],
       [3, 1, 1],
       [3, 5, 4],
       [6, 7, 1],
       [3, 0, 2],
       [3, 6, 1]])

In [4]:
np.hstack((a1,a2))

array([[6, 6, 4, 6, 7, 1],
       [3, 1, 1, 3, 0, 2],
       [3, 5, 4, 3, 6, 1]])

In [5]:
a3 = np.delete(a1, 1,0)

In [6]:
a3

array([[6, 6, 4],
       [3, 5, 4]])

In [7]:
a3 = np.delete(a1, 2,1)

In [8]:
a3

array([[6, 6],
       [3, 1],
       [3, 5]])

In [9]:
np.column_stack((a1,a2))

array([[6, 6, 4, 6, 7, 1],
       [3, 1, 1, 3, 0, 2],
       [3, 5, 4, 3, 6, 1]])

In [10]:
np.row_stack((a1,a2))

array([[6, 6, 4],
       [3, 1, 1],
       [3, 5, 4],
       [6, 7, 1],
       [3, 0, 2],
       [3, 6, 1]])

In [11]:
a5 = np.random.randint(20, size=(10,2))

In [12]:
a5

array([[ 7, 11],
       [ 9, 11],
       [17,  6],
       [ 4,  8],
       [ 0,  2],
       [ 2,  9],
       [13,  8],
       [ 1,  1],
       [14,  5],
       [ 5, 12]])

In [13]:
np.vsplit(a5,5)

[array([[ 7, 11],
        [ 9, 11]]),
 array([[17,  6],
        [ 4,  8]]),
 array([[0, 2],
        [2, 9]]),
 array([[13,  8],
        [ 1,  1]]),
 array([[14,  5],
        [ 5, 12]])]

In [16]:
np.hsplit(a5,2)

[array([[ 7],
        [ 9],
        [17],
        [ 4],
        [ 0],
        [ 2],
        [13],
        [ 1],
        [14],
        [ 5]]),
 array([[11],
        [11],
        [ 6],
        [ 8],
        [ 2],
        [ 9],
        [ 8],
        [ 1],
        [ 5],
        [12]])]

In [17]:
a6 = np.random.randint(20, size=(10,10))
a6

array([[19, 17,  1, 18, 17, 14,  1, 12,  4,  3],
       [ 4, 10, 17,  5, 14,  4,  7,  4, 16,  0],
       [16,  7,  2,  0, 12, 16, 17,  9,  2, 14],
       [11, 16, 13, 18,  5, 10,  8, 14,  3, 15],
       [ 7, 17, 18,  7,  6,  2,  3, 11,  4,  7],
       [16,  9, 17, 12, 14,  3,  5, 14,  0, 16],
       [ 3,  6,  3, 12, 17,  8,  4,  5,  7,  4],
       [ 6,  7, 10, 17, 17,  5, 11, 13, 17,  8],
       [ 9,  2, 19, 14, 13, 11,  2, 14, 18, 14],
       [ 9,  2,  9, 13,  2, 16, 13, 14,  1,  9]])

In [18]:
np.hsplit(a6,5)

[array([[19, 17],
        [ 4, 10],
        [16,  7],
        [11, 16],
        [ 7, 17],
        [16,  9],
        [ 3,  6],
        [ 6,  7],
        [ 9,  2],
        [ 9,  2]]),
 array([[ 1, 18],
        [17,  5],
        [ 2,  0],
        [13, 18],
        [18,  7],
        [17, 12],
        [ 3, 12],
        [10, 17],
        [19, 14],
        [ 9, 13]]),
 array([[17, 14],
        [14,  4],
        [12, 16],
        [ 5, 10],
        [ 6,  2],
        [14,  3],
        [17,  8],
        [17,  5],
        [13, 11],
        [ 2, 16]]),
 array([[ 1, 12],
        [ 7,  4],
        [17,  9],
        [ 8, 14],
        [ 3, 11],
        [ 5, 14],
        [ 4,  5],
        [11, 13],
        [ 2, 14],
        [13, 14]]),
 array([[ 4,  3],
        [16,  0],
        [ 2, 14],
        [ 3, 15],
        [ 4,  7],
        [ 0, 16],
        [ 7,  4],
        [17,  8],
        [18, 14],
        [ 1,  9]])]

In [19]:
np.vsplit(a6,5)

[array([[19, 17,  1, 18, 17, 14,  1, 12,  4,  3],
        [ 4, 10, 17,  5, 14,  4,  7,  4, 16,  0]]),
 array([[16,  7,  2,  0, 12, 16, 17,  9,  2, 14],
        [11, 16, 13, 18,  5, 10,  8, 14,  3, 15]]),
 array([[ 7, 17, 18,  7,  6,  2,  3, 11,  4,  7],
        [16,  9, 17, 12, 14,  3,  5, 14,  0, 16]]),
 array([[ 3,  6,  3, 12, 17,  8,  4,  5,  7,  4],
        [ 6,  7, 10, 17, 17,  5, 11, 13, 17,  8]]),
 array([[ 9,  2, 19, 14, 13, 11,  2, 14, 18, 14],
        [ 9,  2,  9, 13,  2, 16, 13, 14,  1,  9]])]