# Saving and Loading Numpy Objects

In [1]:
import numpy as np
from numpy import random

In [2]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.save('savea1', a1)

In [4]:
a2 = np.load('savea1.npy')

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3 = np.random.randint(1, 20, size=(100,3))

In [7]:
a3

array([[17, 18, 10],
       [11, 16,  3],
       [ 4,  5, 12],
       [10,  3,  7],
       [ 9,  5, 16],
       [ 3, 19,  1],
       [ 8, 18, 15],
       [10,  9, 15],
       [14, 18,  9],
       [ 2,  7, 19],
       [15,  8, 15],
       [13,  5, 17],
       [ 9,  7, 18],
       [ 5,  2, 19],
       [ 4, 19, 18],
       [11,  2, 18],
       [15,  7, 11],
       [13, 13, 13],
       [18, 19, 11],
       [ 5, 19,  7],
       [ 1,  1, 19],
       [14, 14, 18],
       [ 7,  7, 14],
       [ 5, 13,  9],
       [15, 19, 19],
       [17,  3,  3],
       [18,  1, 13],
       [12,  3, 19],
       [13, 11,  1],
       [12, 10,  3],
       [ 8,  4, 12],
       [18,  8, 18],
       [ 8,  4,  6],
       [19,  8, 14],
       [ 8, 16, 12],
       [16,  3, 17],
       [ 7,  1, 18],
       [ 6,  1, 18],
       [17,  6,  8],
       [ 7, 13, 19],
       [ 9, 13, 19],
       [16, 15,  4],
       [ 9,  8,  6],
       [15, 13, 19],
       [12,  1, 18],
       [ 2, 17,  5],
       [ 9, 15, 19],
       [10, 1

In [8]:
np.savetxt('savecsva3.csv', a3)

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('savecsva3.csv')
df

1.700000000000000000e+01 1.800000000000000000e+01 1.000000000000000000e+01
0   1.100000000000000000e+01 1.600000000000000000e...                        
1   4.000000000000000000e+00 5.000000000000000000e...                        
2   1.000000000000000000e+01 3.000000000000000000e...                        
3   9.000000000000000000e+00 5.000000000000000000e...                        
4   3.000000000000000000e+00 1.900000000000000000e...                        
..                                                ...                        
94  1.700000000000000000e+01 8.000000000000000000e...                        
95  9.000000000000000000e+00 1.400000000000000000e...                        
96  1.100000000000000000e+01 4.000000000000000000e...                        
97  1.900000000000000000e+01 5.000000000000000000e...                        
98  1.200000000000000000e+01 1.500000000000000000e...                        

[99 rows x 1 columns]

In [11]:
a4 = np.loadtxt('savecsva3.csv')

In [12]:
a4

array([[17., 18., 10.],
       [11., 16.,  3.],
       [ 4.,  5., 12.],
       [10.,  3.,  7.],
       [ 9.,  5., 16.],
       [ 3., 19.,  1.],
       [ 8., 18., 15.],
       [10.,  9., 15.],
       [14., 18.,  9.],
       [ 2.,  7., 19.],
       [15.,  8., 15.],
       [13.,  5., 17.],
       [ 9.,  7., 18.],
       [ 5.,  2., 19.],
       [ 4., 19., 18.],
       [11.,  2., 18.],
       [15.,  7., 11.],
       [13., 13., 13.],
       [18., 19., 11.],
       [ 5., 19.,  7.],
       [ 1.,  1., 19.],
       [14., 14., 18.],
       [ 7.,  7., 14.],
       [ 5., 13.,  9.],
       [15., 19., 19.],
       [17.,  3.,  3.],
       [18.,  1., 13.],
       [12.,  3., 19.],
       [13., 11.,  1.],
       [12., 10.,  3.],
       [ 8.,  4., 12.],
       [18.,  8., 18.],
       [ 8.,  4.,  6.],
       [19.,  8., 14.],
       [ 8., 16., 12.],
       [16.,  3., 17.],
       [ 7.,  1., 18.],
       [ 6.,  1., 18.],
       [17.,  6.,  8.],
       [ 7., 13., 19.],
       [ 9., 13., 19.],
       [16., 15.